# Generated by Django 4.0.5 on 2023-09-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
