# Generated by Django 4.0.5 on 2023-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_userprofile_is_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.CharField(default=1000000, max_length=20),
        ),
    ]
