# Generated by Django 4.0.5 on 2023-10-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_userprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='profit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
