# Generated by Django 4.0.5 on 2023-10-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_stocks_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='participants',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.CharField(default='1000000', max_length=20),
        ),
    ]
