# Generated by Django 4.0.5 on 2023-10-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_userprofile_participants_alter_userprofile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='bought_price',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='profit',
            field=models.FloatField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='sold_price',
            field=models.FloatField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.FloatField(default=1000000, max_length=20),
        ),
    ]
